### ISSUE TITLE
If dns resolves to IPv6, pop goes the weasel

### ISSUE THREAD

**Issue by boekabart** [boekabart/QuickConnect#13]
```
C:\Users\bartd>tring ender 3389 -w
| Time              | IP or hostname  | Port  | Protocol | Connect | Ping    | Local Interface |
| 10:23:33-10:23:46 | DNS timeout     | 3389  | rdp      |         | -       |                 |

Unhandled Exception: System.NotSupportedException: This protocol version is not supported.
   at System.Net.Sockets.Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at Tring.ConnectionTester.TryConnect() in C:\Users\bartd\Sandbox\Hightech\Tring\src\Tring\ConnectionTester.cs:line 68
   at Tring.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\Users\bartd\Sandbox\Hightech\Tring\src\Tring\Program.cs:line 58
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tring.Program.Main(String[] args) in C:\Users\bartd\Sandbox\Hightech\Tring\src\Tring\Program.cs:line 84
```
Theory: IPv6.
In this case, `ping ender` will resolve to an IPv6 address.
EITHER we should support connecting and pinging addresses resolved to IPv6 as well, OR we should force the DNS lookup to be IPv4 (at least for the time being).

The latter is my current suggestion, then, create an issue for IPv6 support, with the feature to force v4/v6 with the `-4` or  `-6` command line param as ping does it.

**Comment by kees2125** [comment]
Currently it forces IPv4, I've added a issue to add support for IPv6 later on.
